name: 'Frontend tests'
on:
  push:
    branches: [main, dev, CI/CD]

jobs:
  FE_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: ./Frontend
        run: npm i
      - name: Run tests
        working-directory: ./Frontend
        run: npx run test